// RutaLibre · datos de rutas para rutas.html

(function () {
  'use strict';

  const PHONE = '5355335946';

  const ROUTES = [
    {
      key: 'airport',
      id: 'airport',
      categories: ['aeropuerto'],
      featured: true,
      image: 'assets/Areopuerto.jpg',
      imageWidth: 2048,
      imageHeight: 1536,
      imageClass: 'img-dark',
      alt: {
        es: 'Traslado aeropuerto José Martí La Habana',
        en: 'José Martí Airport transfer in Havana',
        fr: 'Transfert aéroport José Martí à La Havane',
      },
      pillCount: 3,
      bluePills: [2],
      buttonType: 'airport',
    },
    {
      key: 'varadero',
      id: 'varadero',
      categories: ['playa'],
      featured: true,
      image: 'assets/Playa-de-Varadero-Cuba.jpg',
      imageWidth: 950,
      imageHeight: 722,
      alt: {
        es: 'Playa de Varadero Cuba — transporte privado desde La Habana',
        en: 'Varadero beach in Cuba — private transport from Havana',
        fr: 'Plage de Varadero à Cuba — transport privé depuis La Havane',
      },
      pillCount: 3,
      bluePills: [2],
    },
    {
      key: 'vinales',
      id: 'vinales',
      categories: ['naturaleza'],
      image: 'assets/mural-vinales.jpg',
      imageWidth: 950,
      imageHeight: 629,
      alt: {
        es: 'Valle de Viñales Cuba — transporte privado desde La Habana',
        en: 'Viñales Valley in Cuba — private transport from Havana',
        fr: 'Vallée de Viñales à Cuba — transport privé depuis La Havane',
      },
      pillCount: 2,
      bluePills: [2],
    },
    {
      key: 'trinidad',
      id: 'trinidad',
      categories: ['colonial'],
      image: 'assets/trinidad-cuba-old-centre.jpg',
      imageWidth: 750,
      imageHeight: 490,
      alt: {
        es: 'Trinidad ciudad colonial Cuba — transporte desde La Habana',
        en: 'Trinidad colonial city in Cuba — transport from Havana',
        fr: 'Trinidad ville coloniale à Cuba — transport depuis La Havane',
      },
      pillCount: 2,
      bluePills: [2],
    },
    {
      key: 'cayo_santa_maria',
      id: 'cayo-santa-maria',
      categories: ['playa'],
      image: 'assets/cayo santa maria.avif',
      imageWidth: 2000,
      imageHeight: 1000,
      alt: {
        es: 'Cayo Santa María Cuba — transporte privado',
        en: 'Cayo Santa Maria Cuba — private transport',
        fr: 'Cayo Santa María Cuba — transport privé',
      },
      pillCount: 2,
      bluePills: [2],
    },
    {
      key: 'zapata',
      id: 'zapata',
      categories: ['naturaleza'],
      image: 'assets/cienaga de zapata.jpg',
      imageWidth: 847,
      imageHeight: 491,
      alt: {
        es: 'Ciénaga de Zapata Cuba naturaleza',
        en: 'Zapata Swamp nature in Cuba',
        fr: 'Marais de Zapata nature à Cuba',
      },
      pillCount: 2,
      bluePills: [2],
    },
    {
      key: 'cayo_coco',
      id: 'cayo-coco',
      categories: ['playa'],
      image: 'assets/cayo coco.jpg',
      imageWidth: 1296,
      imageHeight: 864,
      alt: {
        es: 'Cayo Coco Cuba playa resort',
        en: 'Cayo Coco Cuba beach resort',
        fr: 'Cayo Coco Cuba plage et resort',
      },
      pillCount: 2,
      bluePills: [2],
    },
    {
      key: 'guardalavaca',
      id: 'guardalavaca',
      categories: ['playa'],
      image: 'assets/guardalavaca.jpg',
      imageWidth: 1900,
      imageHeight: 720,
      alt: {
        es: 'Guardalavaca playa Cuba menos concurrida',
        en: 'Guardalavaca beach in Cuba, less crowded',
        fr: 'Plage de Guardalavaca à Cuba, moins fréquentée',
      },
      pillCount: 2,
      bluePills: [2],
    },
    {
      key: 'topes',
      id: 'topes-de-collantes',
      categories: ['naturaleza'],
      image: 'assets/topes de collantes.jpg',
      imageWidth: 1024,
      imageHeight: 683,
      alt: {
        es: 'Topes de Collantes cascadas Cuba',
        en: 'Topes de Collantes waterfalls in Cuba',
        fr: 'Cascades de Topes de Collantes à Cuba',
      },
      pillCount: 2,
      bluePills: [2],
    },
    {
      key: 'el_nicho',
      id: 'el-nicho',
      categories: ['naturaleza'],
      image: 'assets/el nicho.jpg',
      imageWidth: 1200,
      imageHeight: 900,
      alt: {
        es: 'El Nicho cascadas Cuba Sierra del Escambray',
        en: 'El Nicho waterfalls in Cuba, Escambray Mountains',
        fr: 'Cascades El Nicho à Cuba, Sierra del Escambray',
      },
      pillCount: 2,
      bluePills: [2],
    },
    {
      key: 'santiago',
      id: 'santiago',
      categories: ['larga', 'colonial'],
      image: 'assets/santiago.jpg',
      imageWidth: 540,
      imageHeight: 312,
      alt: {
        es: 'Santiago de Cuba transporte privado desde La Habana',
        en: 'Santiago de Cuba private transport from Havana',
        fr: 'Santiago de Cuba transport privé depuis La Havane',
      },
      pillCount: 2,
      bluePills: [2],
    },
    {
      key: 'cienfuegos',
      id: 'cienfuegos',
      categories: ['colonial'],
      image: 'assets/cienfuego.jpg',
      imageWidth: 739,
      imageHeight: 415,
      alt: {
        es: 'Cienfuegos La Perla del Sur Cuba',
        en: 'Cienfuegos, Pearl of the South, Cuba',
        fr: 'Cienfuegos, la Perle du Sud, Cuba',
      },
      pillCount: 2,
      bluePills: [2],
    },
  ];

  window.RL_ROUTES = { phone: PHONE, items: ROUTES };
})();
